### ISSUE TITLE
ContentResolver.requestSync() not calls the SyncService on SDK 26.

### ISSUE THREAD

**Issue by Mokshi1709** [googlesamples/android-BasicSyncAdapter#11]
The app is working as expected upto Lollipop version. (i.e:) It takes data from the content provider and post to Server when network connectivity is available.

The **issue occur from Marshmallow version**, The requestSync() is not triggering onPerformSync(). So Syncing not occurs. Provide suggestion in this case.

**Comment by August1996** [comment]
i meet the same problem with api26,but it works below api26.

**Comment by miamilabs** [comment]
> i meet the same problem with api26,but it works below api26.

did you found a solution for that? on SDK 28 its not working form me as well.

**Comment by saleo** [comment]
mine failed from API 26+, and it seems related to "limit on background service running" ,which was introduced in Oreo+..

but whats confusing is the official doc says, "bound service not limited by these rules", while the syncAdapterService works as bound service,just as the official sample and docs show...

**Comment by ashish-patidar-rau** [comment]
i also facing the problem in API 28
- SyncService Created : successfully
- SyncService Bind : successfully
- SyncAdapter Created : successfully

!!! but SyncAdapter Not Called !!! 

please provide the solution for that

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
