### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by abhishek0196** [googlesamples/android-BasicSyncAdapter#14]
![screenshot 2](https://user-images.githubusercontent.com/13505029/53726767-b4bedd00-3e94-11e9-8077-433e80d916e2.png)

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
