### ISSUE TITLE
EntryListActivity.class requires API 8 sample set to api 7

### ISSUE THREAD

**Issue by CrandellWS** [googlesamples/android-BasicSyncAdapter#2]
See :

https://github.com/googlesamples/android-BasicSyncAdapter/blob/master/Application/tests/src/com/example/android/basicsyncadapter/tests/SampleTests.java#L31

https://github.com/googlesamples/android-BasicSyncAdapter/blob/master/Application/build.gradle#L37

it builds and runs on device api 19 fine... It is unknown to me what the difference is...more research is required, or someone who already knows...

Can this be fixed with 

```
int currentapiVersion = android.os.Build.VERSION.SDK_INT;
if (currentapiVersion >= android.os.Build.VERSION_CODES.FROYO){
    super(EntryListActivity.class);
} else{
    // ??
}
```

or 

```

int currentapiVersion = Build.VERSION.SDK_INT;
if (currentapiVersion >= Build.VERSION_CODES.FROYO){
    super(EntryListActivity.class);
} else{
    // ??
}
```

Granted personally I no longer support Froyo...

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
