### ISSUE TITLE
Changing from ListFragment to Fragment w/ RecyclerView

### ISSUE THREAD

**Issue by seventhmoon** [googlesamples/android-BasicSyncAdapter#3]
I know it is a sample, and implementation is simple. But since RecyclerView (aka ListView2) is introduced and have better memory usage. Could this sample have a code update so it becomes a "practice" for using RecyclerView rather than ListView / ListFragment?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
