### ISSUE TITLE
Target new version of SDK and add Run-time Permission Request

### ISSUE THREAD

**Issue by seventhmoon** [googlesamples/android-BasicSyncAdapter#4]
The project has targetSdk = 22, which is not the newest version.
The project does not implement Run-time Permission model of Android 6.0

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
