### ISSUE TITLE
Minimum frequency for PeriodicSync

### ISSUE THREAD

**Issue by wwahmed** [googlesamples/android-BasicSyncAdapter#5]
`I came here from Android Issue (https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&groupby=&sort=&id=211975) logged against Android N Developer preview. 

This project was used as an example to demonstrate the issue. 

Is the implication of the comments from Google Issue is that PeridicSync cannot be used if a sync is desired more frequently than 60 minutes ? Is there an alternative available to achieve this effect that you might be considering adding to this project?

**Comment by aladdin-im** [comment]
<img width="1123" alt="qq20190111-172134 2x" src="https://user-images.githubusercontent.com/2290475/51024792-74925b00-15c5-11e9-9de9-fa4abb0a312c.png">

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
