### ISSUE TITLE
can not perform sync on sdk 26

### ISSUE THREAD

**Issue by bTuzi** [googlesamples/android-BasicSyncAdapter#9]
I have a problem about syncing emails on Android 8.0.0 released on 10.5.On the app "Gmail",mailboxes is synced ,emails can not be synced. On the demo,I found no matter click syncing icon or click syncing icon in the Setting, the method onPerformSync in class SyncAdapter did not executed.I tried many methods  such as modify the xml,add or delete params in syncing methods  but they did not work. ps:all these things turns to be right if I run apps on SDK 7.0 or 6.0,and logcat tells me nothing .

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
